name: themovie_db
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  cupertino_icons: ^1.0.2
  spider: ^2.2.2
  json_annotation: ^4.5.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  youtube_player_flutter: ^8.1.0
  font_awesome_flutter: ^10.1.0
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11


flutter:

  uses-material-design: true

  assets:
    - images/
  